import { writeManagedFile } from '../git-updates';
import { dirname, join, relative } from 'node:path';
import { mkdir } from 'node:fs/promises';
import { configError, parseRootConfig, relativeOutput, schemaForTarget, upsertSetting, type RootConfig } from '../config';
import { preflightPaths, type OutputPath } from '../output-paths';
import { removeEnvironmentFromContent, resolveEnvironment, upsertEnvironmentInContent } from '../environment';
import { generateLocalEnvContent, parseHeader } from '../parser';
import type { CommandContext, EnvVarSchema } from '../types';
import { EnvManagerError } from '../types';
import { generateSwiftValuesContent, readValuesForConfig, resolveValuesConfig, type ValuesConfig } from '../values-config';
import { validateEnv } from '../validator';

const DEFAULT_OUTPUT_PATH = 'src/env.ts';

const HEADER = `// AUTO-GENERATED by \`env-manager generate\` - do not edit
import { z } from 'zod';

const env = z.object({
`;

const FOOTER = `}).parse(process.env);

export default env;
`;

function generateZodField(s: EnvVarSchema): string {
  let chain = '';

  switch (s.type) {
    case 'string':
      chain = 'z.string()';
      break;
    case 'int':
      chain = 'z.coerce.number().int()';
      break;
    case 'float':
      chain = 'z.coerce.number()';
      break;
    case 'bool':
      chain = 'z.stringbool()';
      break;
    case 'url':
      chain = 'z.url()';
      break;
    case 'email':
      chain = 'z.email()';
      break;
    case 'file':
      chain = 'z.string()';
      break;
  }

  for (const v of s.validators) {
    if (v.kind === 'min') chain += `.min(${v.value})`;
    if (v.kind === 'max') chain += `.max(${v.value})`;
    if (v.kind === 'format') chain += `.regex(${v.pattern.toString()})`;
  }

  if (s.optional) {
    chain += '.optional()';
  }

  return `  ${s.name}: ${chain},`;
}

export function generateReader(schema: EnvVarSchema[]): string {
  return HEADER + schema.map(generateZodField).join('\n') + '\n' + FOOTER;
}

type PlannedOutput = OutputPath & { schema: EnvVarSchema[]; kind: 'reader' | 'values'; format: 'ts' | 'swift' };
export type GenerationPlan = { config: RootConfig; valuesConfig: ValuesConfig; outputs: PlannedOutput[] };

export async function planGeneration(ctx: CommandContext, content: string): Promise<GenerationPlan> {
  const file = join(ctx.cwd, '.env');
  const config = parseRootConfig(content, file);
  if (config.header && config.header.project !== ctx.project) configError(file, 1, `.env project "${config.header.project}" does not match --project "${ctx.project}".`);
  const valuesConfig = await resolveValuesConfig(ctx, content);
  const outputs: PlannedOutput[] = [];
  if (config.targets.length) {
    for (const target of config.targets) {
      const directory = join(ctx.cwd, target.name);
      const schema = schemaForTarget(config, target.name);
      outputs.push({ path: join(directory, target.path), directory, line: target.line, target: target.name, schema, kind: 'values', format: target.format });
      if (target.generate) outputs.push({ path: join(directory, target.generate), directory, line: target.line, target: target.name, schema, kind: 'reader', format: 'ts' });
    }
    outputs.push({ path: join(ctx.cwd, valuesConfig.path), directory: ctx.cwd, line: 1, source: true, schema: config.schema, kind: 'values', format: 'ts' });
  } else {
    relativeOutput(valuesConfig.path, file, 1);
    outputs.push({ path: join(ctx.cwd, valuesConfig.path), directory: ctx.cwd, line: 1, source: true, schema: config.schema, kind: 'values', format: valuesConfig.format });
    if (valuesConfig.format === 'ts') {
      const path = relativeOutput(config.generate ?? DEFAULT_OUTPUT_PATH, file, 1);
      outputs.push({ path: join(ctx.cwd, path), directory: ctx.cwd, line: 1, schema: config.schema, kind: 'reader', format: 'ts' });
    }
  }
  await preflightPaths(ctx, outputs, valuesConfig.path);
  return { config, outputs, valuesConfig };
}

function ownership(ctx: CommandContext, output: PlannedOutput, environment: string, date: string): string {
  const prefix = output.format === 'swift' || output.kind === 'reader' ? '//' : '#';
  return [
    `${prefix} env-manager: ${ctx.project}${date ? ` | ${date}` : ''}`,
    `${prefix} env-manager target: ${output.target}`,
    `${prefix} env-manager root: ${relative(dirname(output.path), ctx.cwd) || '.'}`,
    `${prefix} env-manager env: ${environment}`,
    '',
  ].join('\n');
}

async function materializePlan(ctx: CommandContext, plan: GenerationPlan, targetName?: string): Promise<void> {
  if (targetName && !plan.config.targets.some(t => t.name === targetName)) configError(join(ctx.cwd, '.env'), 1, `Unknown target "${targetName}".`);
  const values = await readValuesForConfig(ctx, plan.valuesConfig);
  const environment = await resolveEnvironment(ctx.cwd, { valuesPath: plan.valuesConfig.format === 'ts' ? plan.valuesConfig.path : undefined });
  const sourceFile = Bun.file(join(ctx.cwd, plan.valuesConfig.path));
  const sourceExists = await sourceFile.exists();
  const sourceContent = sourceExists ? await sourceFile.text() : '';
  const sourceDate = sourceContent.split('\n').map(parseHeader).find(Boolean)?.syncDate;
  const date = sourceExists ? sourceDate || plan.config.header?.syncDate || '' : new Date().toISOString();
  for (const entry of plan.config.schema) {
    const value = values[entry.name] ?? entry.defaultValue;
    if (value !== null && value !== undefined && value !== '') {
      const result = validateEnv([entry], { [entry.name]: value });
      if (!result.valid) configError(join(ctx.cwd, plan.valuesConfig.path), 1, `Invalid value for ${entry.name}: ${result.errors[0].message}`);
    }
  }
  const writes: { path: string; content: string }[] = [];
  for (const output of plan.outputs) {
    if (targetName && output.target && output.target !== targetName) continue;
    if (output.source && sourceExists) continue;
    const selectedValues: Record<string, string> = {};
    for (const entry of output.schema) selectedValues[entry.name] = values[entry.name] ?? entry.defaultValue ?? '';
    let content = output.kind === 'reader' ? generateReader(output.schema) : output.format === 'swift'
      ? generateSwiftValuesContent(output.schema, selectedValues)
      : generateLocalEnvContent(output.schema, selectedValues, { project: ctx.project, syncDate: date });
    if (output.target) {
      if (output.kind === 'values' && output.format === 'ts') content = generateLocalEnvContent(output.schema, selectedValues);
      content = ownership(ctx, output, environment, date) + content;
    } else if (output.kind === 'values' && output.format === 'ts') content = upsertEnvironmentInContent(content, environment);
    writes.push({ path: output.path, content });
  }
  for (const write of writes) {
    await mkdir(dirname(write.path), { recursive: true });
    if (await Bun.file(write.path).exists() && await Bun.file(write.path).text() === write.content) continue;
    await writeManagedFile(write.path, write.content);
    console.log(`Generated ${relative(ctx.cwd, write.path)}`);
  }
}

export async function generateCommand(
  ctx: CommandContext,
  outputPath?: string,
  options: { force?: boolean; target?: string } = {}
): Promise<void> {
  const envPath = join(ctx.cwd, '.env');
  if (!(await Bun.file(envPath).exists())) throw new EnvManagerError(`.env not found at ${envPath}`);
  const original = await Bun.file(envPath).text();
  let content = removeEnvironmentFromContent(original);
  const config = parseRootConfig(content, envPath);
  if (!config.targets.length) {
    if (options.target) configError(envPath, 1, '--target requires target declarations.');
    const valuesConfig = await resolveValuesConfig(ctx, content);
    if (outputPath && valuesConfig.format !== 'ts') configError(envPath, 1, 'A reader output path only works when values.format is "ts".');
    if (outputPath) relativeOutput(outputPath, envPath, 1);
    if (outputPath && config.generate && outputPath !== config.generate && !options.force) configError(envPath, 1, `.env has ts path "${config.generate}" but "${outputPath}" was given. Pass --force to overwrite.`);
    if (!config.schema.length) configError(envPath, 1, 'No schema found in .env. Add schema comments like: # {string}');
    if (valuesConfig.format === 'ts' && (outputPath || config.generate || !config.modern)) content = upsertSetting(content, config.modern ? 'generate' : 'ts', outputPath ?? config.generate ?? DEFAULT_OUTPUT_PATH);
  } else if (outputPath) {
    if (!options.target) configError(envPath, 1, 'Use --target <name> with a positional reader path in a monorepo.');
    const target = config.targets.find(t => t.name === options.target);
    if (!target || target.format !== 'ts') configError(envPath, 1, 'A reader path requires a TypeScript target.');
    const path = relativeOutput(outputPath, envPath, target.line);
    if (path !== target.generate && !options.force) configError(envPath, target.line, 'Pass --force to overwrite the target generation path.');
    const lines = content.split('\n');
    const declaration = lines[target.line - 1].replace(/\s+generate=\S+/, '');
    lines[target.line - 1] = `${declaration} generate=${path}`;
    content = lines.join('\n');
  }
  const plan = await planGeneration(ctx, content);
  await materializePlan(ctx, plan, options.target);
  if (content !== original) await writeManagedFile(envPath, content);
}

export async function updateConfiguredTsOutput(ctx: CommandContext, envContent: string): Promise<void> {
  const config = parseRootConfig(envContent, join(ctx.cwd, '.env'));
  if (config.targets.length) {
    await materializePlan(ctx, await planGeneration(ctx, envContent));
  } else if (config.generate || config.modern) {
    const plan = await planGeneration(ctx, envContent);
    for (const output of plan.outputs.filter(o => o.kind === 'reader')) {
      await mkdir(dirname(output.path), { recursive: true });
      await writeManagedFile(output.path, generateReader(output.schema));
      console.log(`Generated ${relative(ctx.cwd, output.path)}`);
    }
  }
}
