import { parseEnvFile } from '../parser';
import type { CommandContext, EnvVarSchema } from '../types';
import { EnvManagerError } from '../types';

const HEADER = `// AUTO-GENERATED by \`env-manager ts\` - do not edit
import { z } from 'zod';

const env = z.object({
`;

const FOOTER = `}).parse(process.env);

export default env;
`;

function generateZodField(s: EnvVarSchema): string {
  let chain = '';

  switch (s.type) {
    case 'string':
      chain = 'z.string()';
      break;
    case 'int':
      chain = 'z.coerce.number().int()';
      break;
    case 'float':
      chain = 'z.coerce.number()';
      break;
    case 'bool':
      chain = 'z.stringbool()';
      break;
    case 'url':
      chain = 'z.url()';
      break;
    case 'email':
      chain = 'z.email()';
      break;
    case 'file':
      chain = 'z.string()';
      break;
  }

  for (const v of s.validators) {
    if (v.kind === 'min') chain += `.min(${v.value})`;
    if (v.kind === 'max') chain += `.max(${v.value})`;
    if (v.kind === 'format') chain += `.regex(${v.pattern.toString()})`;
  }

  if (s.optional) {
    chain += '.optional()';
  }

  return `  ${s.name}: ${chain},`;
}

export async function tsCommand(
  ctx: CommandContext,
  outputPath?: string
): Promise<void> {
  const envPath = `${ctx.cwd}/.env`;
  const outPath = outputPath ?? `${ctx.cwd}/src/env.ts`;

  const envFile = Bun.file(envPath);
  if (!(await envFile.exists())) {
    throw new EnvManagerError(`.env not found at ${envPath}`);
  }

  const content = await envFile.text();
  const parsed = parseEnvFile(content);

  if (parsed.header && parsed.header.project !== ctx.project) {
    throw new EnvManagerError(
      `.env project "${parsed.header.project}" does not match --project "${ctx.project}"`
    );
  }

  if (parsed.schema.length === 0) {
    throw new EnvManagerError(
      'No schema found in .env. Add schema comments like: # {string}'
    );
  }

  const fields = parsed.schema.map(generateZodField).join('\n');
  const output = HEADER + fields + '\n' + FOOTER;

  await Bun.write(outPath, output);
  console.log(`Generated ${outPath}`);
}
