import { parseEnvFile } from '../parser';
import type { CommandContext, EnvVarSchema } from '../types';
import { EnvManagerError } from '../types';

const TS_PATH_COMMENT_PREFIX = '# env-manager ts: ';
const DEFAULT_OUTPUT_PATH = 'src/env.ts';

const HEADER = `// AUTO-GENERATED by \`env-manager ts\` - do not edit
import { z } from 'zod';

const env = z.object({
`;

const FOOTER = `}).parse(process.env);

export default env;
`;

function generateZodField(s: EnvVarSchema): string {
  let chain = '';

  switch (s.type) {
    case 'string':
      chain = 'z.string()';
      break;
    case 'int':
      chain = 'z.coerce.number().int()';
      break;
    case 'float':
      chain = 'z.coerce.number()';
      break;
    case 'bool':
      chain = 'z.stringbool()';
      break;
    case 'url':
      chain = 'z.url()';
      break;
    case 'email':
      chain = 'z.email()';
      break;
    case 'file':
      chain = 'z.string()';
      break;
  }

  for (const v of s.validators) {
    if (v.kind === 'min') chain += `.min(${v.value})`;
    if (v.kind === 'max') chain += `.max(${v.value})`;
    if (v.kind === 'format') chain += `.regex(${v.pattern.toString()})`;
  }

  if (s.optional) {
    chain += '.optional()';
  }

  return `  ${s.name}: ${chain},`;
}

function parseTsPathFromEnv(content: string): string | null {
  const lines = content.split('\n');
  for (const line of lines) {
    if (line.startsWith(TS_PATH_COMMENT_PREFIX)) {
      return line.slice(TS_PATH_COMMENT_PREFIX.length).trim();
    }
  }
  return null;
}

function upsertTsPathInEnv(content: string, tsPath: string): string {
  const comment = `${TS_PATH_COMMENT_PREFIX}${tsPath}`;
  const lines = content.split('\n');

  const existingIdx = lines.findIndex((l) =>
    l.startsWith(TS_PATH_COMMENT_PREFIX)
  );
  if (existingIdx !== -1) {
    lines[existingIdx] = comment;
    return lines.join('\n');
  }

  const headerIdx = lines.findIndex((l) => /^#\s*env-manager:/.test(l));
  if (headerIdx !== -1) {
    lines.splice(headerIdx + 1, 0, comment);
    return lines.join('\n');
  }

  return comment + '\n' + content;
}

export async function tsCommand(
  ctx: CommandContext,
  outputPath?: string,
  options?: { force?: boolean }
): Promise<void> {
  const envPath = `${ctx.cwd}/.env`;

  const envFile = Bun.file(envPath);
  if (!(await envFile.exists())) {
    throw new EnvManagerError(`.env not found at ${envPath}`);
  }

  const content = await envFile.text();
  const storedPath = parseTsPathFromEnv(content);

  if (outputPath && storedPath && outputPath !== storedPath && !options?.force) {
    throw new EnvManagerError(
      `.env has ts path "${storedPath}" but "${outputPath}" was given. Pass --force to overwrite.`
    );
  }

  const outPath = outputPath ?? storedPath ?? DEFAULT_OUTPUT_PATH;
  const parsed = parseEnvFile(content);

  if (parsed.header && parsed.header.project !== ctx.project) {
    throw new EnvManagerError(
      `.env project "${parsed.header.project}" does not match --project "${ctx.project}"`
    );
  }

  if (parsed.schema.length === 0) {
    throw new EnvManagerError(
      'No schema found in .env. Add schema comments like: # {string}'
    );
  }

  const fields = parsed.schema.map(generateZodField).join('\n');
  const output = HEADER + fields + '\n' + FOOTER;

  await Bun.write(outPath, output);

  const updatedEnv = upsertTsPathInEnv(content, outPath);
  await Bun.write(envPath, updatedEnv);

  console.log(`Generated ${outPath}`);
}
