import { parseEnvFile } from "../parser";
import type { CommandContext, EnvVarSchema } from "../types";
import { EnvManagerError } from "../types";

const HEADER = `// AUTO-GENERATED by \`env-manager ts\` - do not edit
import { z } from "zod";

const envSchema = z.object({
`;

const FOOTER = `});

const env = envSchema.parse(process.env);

export default env;
`;

function generateZodField(s: EnvVarSchema): string {
  let chain = "";

  switch (s.type) {
    case "string":
      chain = "z.string()";
      break;
    case "int":
      chain = "z.coerce.number().int()";
      break;
    case "float":
      chain = "z.coerce.number()";
      break;
    case "bool":
      chain = "z.coerce.boolean()";
      break;
    case "url":
      chain = "z.string().url()";
      break;
    case "email":
      chain = "z.string().email()";
      break;
    case "file":
      chain = "z.string()";
      break;
  }

  for (const v of s.validators) {
    if (v.kind === "min") chain += `.min(${v.value})`;
    if (v.kind === "max") chain += `.max(${v.value})`;
    if (v.kind === "format") chain += `.regex(${v.pattern.toString()})`;
  }

  if (s.optional) {
    chain += ".optional()";
  }

  if (s.defaultValue !== null) {
    let defaultVal: string;
    if (s.type === "int" || s.type === "float") {
      defaultVal = s.defaultValue;
    } else if (s.type === "bool") {
      const lower = s.defaultValue.toLowerCase();
      defaultVal = ["true", "1", "yes", "on"].includes(lower)
        ? "true"
        : "false";
    } else {
      defaultVal = JSON.stringify(s.defaultValue);
    }
    chain += `.default(${defaultVal})`;
  }

  return `  ${s.name}: ${chain},`;
}

export async function tsCommand(
  ctx: CommandContext,
  outputPath?: string
): Promise<void> {
  const envPath = `${ctx.cwd}/.env`;
  const outPath = outputPath ?? `${ctx.cwd}/src/env.ts`;

  const envFile = Bun.file(envPath);
  if (!(await envFile.exists())) {
    throw new EnvManagerError(`.env not found at ${envPath}`);
  }

  const content = await envFile.text();
  const parsed = parseEnvFile(content);

  if (parsed.header && parsed.header.project !== ctx.project) {
    throw new EnvManagerError(
      `.env project "${parsed.header.project}" does not match --project "${ctx.project}"`
    );
  }

  if (parsed.schema.length === 0) {
    throw new EnvManagerError(
      "No schema found in .env. Add schema comments like: # {string}"
    );
  }

  const fields = parsed.schema.map(generateZodField).join("\n");
  const output = HEADER + fields + "\n" + FOOTER;

  await Bun.write(outPath, output);
  console.log(`Generated ${outPath}`);
}
