// AUTO-GENERATED by `env-manager ts` - do not edit
import { z } from 'zod';

const env = z.object({
  AWS_ACCESS_KEY_ID: z.string(),
  AWS_SECRET_ACCESS_KEY: z.string(),
  AWS_REGION: z.string(),
  AWS_DEFAULT_REGION: z.string(),
  OPENROUTER_MANAGEMENT_KEY: z.string().regex(/^sk-or-/),
  OPENROUTER_API_KEY: z.string().regex(/^sk-or-v1-/),
}).parse(process.env);

export default env;
