// AUTO-GENERATED by `env-manager ts` - do not edit
import { z } from "zod";

const envSchema = z.object({
  AWS_ACCESS_KEY_ID: z.string(),
  AWS_SECRET_ACCESS_KEY: z.string(),
  AWS_REGION: z.string(),
  AWS_DEFAULT_REGION: z.string(),
  OPENROUTER_MANAGEMENT_KEY: z.string().regex(/^sk-or-/),
});

const env = envSchema.parse(process.env);

export default env;
